/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigos.telas;

import codigos.bd.Banco;
import codigos.bd.beans.Cidades;
import codigos.bd.beans.Estados;
import codigos.bd.beans.Versao;
import codigos.bd.models.CidadesModel;
import codigos.bd.models.EstadosModel;
import codigos.bd.models.VersaoModel;
import codigos.telas.modal.ModalityInternalFrame;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import javax.swing.JDesktopPane;

/**
 *
 * @author Lucas
 */
public class BancoDados extends ModalityInternalFrame {

    /**
     * Creates new form BancoDados
     */
    public BancoDados(JDesktopPane main) {
        super(main, "Rotinas de Bando de Dados", false, true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Senha:");

        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
            }
        });

        jButton1.setText("Executar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        executar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            executar();
        }
    }//GEN-LAST:event_jPasswordField1KeyPressed

    private void executar() {
        if (new String(jPasswordField1.getPassword()).compareTo("147258369") == 0) {
            try {
                jTextArea1.removeAll();
                
                //se não criar o banco quer dizer q ele ja existe, ai verifica a versão
                if (!criarBanco()) {

                }
            } catch (SQLException ex) {
                jTextArea1.setText(ex.toString());
            } catch (ClassNotFoundException ex) {
                jTextArea1.setText(ex.toString());
            }
        } else {
            jTextArea1.setText("Senha inválida");
        }
    }

    private boolean criarBanco() throws SQLException, ClassNotFoundException {
        Banco banco = new Banco();
        banco.getConnection();
        
        
        if (banco.exists()) {
            jTextArea1.setText("Banco de Dados já existe!");
            return false;
        }

        EstadosModel em = new EstadosModel();
        CidadesModel cm = new CidadesModel();
        VersaoModel vm = new VersaoModel();

        

        jTextArea1.setText(banco.createTableEstados() + "\n");
        jTextArea1.append(banco.createTableCidades() + "\n");
        jTextArea1.append(banco.createTableClientes() + "\n");
        jTextArea1.append(banco.createTableEnderecos() + "\n");
        jTextArea1.append(banco.createTablePagamentos() + "\n");
        jTextArea1.append(banco.createTableProdutos() + "\n");
        jTextArea1.append(banco.createTableVendas() + "\n");
        jTextArea1.append(banco.createTableVendasHasProdutos() + "\n");
        jTextArea1.append(banco.createTableVersao() + "\n");

        int id = em.inserir(new Estados(null, "São Paulo", "SP"));
        jTextArea1.append("Estado de São Paulo inserido!\n");

        cm.inserir(new Cidades(null, id, "Ribeirão Preto"));
        cm.inserir(new Cidades(null, id, "Sertãozinho"));
        cm.inserir(new Cidades(null, id, "Dumont"));
        cm.inserir(new Cidades(null, id, "Altinópolis"));
        jTextArea1.append("Cidades de São Paulos inseridas!\n");

        id = em.inserir(new Estados(null, "Minas Gerais", "MG"));
        jTextArea1.append("Estado de Minas Gerais inserido!\n");

        cm.inserir(new Cidades(null, id, "Belo Horizonte"));
        jTextArea1.append("Cidades de Minas Gerais inseridas!\n");

        vm.inserir(new Versao(null, "1.0.0", null));

        jTextArea1.append("Banco de Dados criado com sucesso! Versão 1.0.0\n");
        return true;

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
