/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigos.telas;

import codigos.telas.relatorio.Relatorio;
import codigos.bd.beans.Cidades;
import codigos.bd.beans.Clientes;
import codigos.bd.beans.Enderecos;
import codigos.bd.beans.Estados;
import codigos.bd.models.CidadesModel;
import codigos.bd.models.ClientesModel;
import codigos.bd.models.EnderecosModel;
import codigos.bd.models.EstadosModel;
import codigos.telas.relatorio.ClientesRelatorio;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDesktopPane;
import javax.swing.JFileChooser;

/**
 *
 * @author Lucas
 */
public class RelatorioClientes extends Relatorio {

    private ClientesModel clientesModel;
    private ArrayList<Clientes> clientesArray;

    /**
     * Creates new form Relatorio
     */
    public RelatorioClientes(JDesktopPane main) throws SQLException, ClassNotFoundException {
        super(main, "Relatório de Clientes");
        clientesModel = new ClientesModel();
        clientesArray = clientesModel.getAll();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Relatório de Clientes");

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Filtrar:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos", "Pai", "Mãe" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jComboBox2.setVisible(false);
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        if (fileChooser.showSaveDialog(parent) == JFileChooser.APPROVE_OPTION) {
            int index = jComboBox1.getSelectedIndex();
            String arquivo = fileChooser.getSelectedFile().getPath() + ".pdf";

            String relatorio = "";

            ArrayList<Clientes> dados = null;

            if (index == 0) {
                dados = clientesArray;
                relatorio = "relatorios/RelatorioClientes.jrxml";
            } else {
                dados = new ArrayList<>();

                index = jComboBox2.getSelectedIndex();

                ClientesRelatorio clientes = new ClientesRelatorio();
                clientes.setId(clientesArray.get(index).getId());

                clientes.setNome(clientesArray.get(index).getNome());
                clientes.setDataNascimento(clientesArray.get(index).getDataNascimento());
                clientes.setDataCadastro(clientesArray.get(index).getDataCadastro());
                clientes.setSexo(clientesArray.get(index).getSexo());

                clientes.setNomePai(clientesArray.get(index).getNomePai());
                clientes.setEmailPai(clientesArray.get(index).getEmailPai());
                clientes.setFacebookPai(clientesArray.get(index).getFacebookPai());
                clientes.setCpfPai(formatar("###.###.###-##", clientesArray.get(index).getCpfPai()));
                clientes.setTelResPai(formatar("(##) ####-####", clientesArray.get(index).getTelResPai()));
                clientes.setTelCelPai(formatar("(##) #####-####", clientesArray.get(index).getTelCelPai()));

                clientes.setNomeMae(clientesArray.get(index).getNomeMae());
                clientes.setEmailMae(clientesArray.get(index).getEmailMae());
                clientes.setFacebookMae(clientesArray.get(index).getFacebookMae());
                clientes.setCpfMae(formatar("###.###.###-##", clientesArray.get(index).getCpfMae()));
                clientes.setTelResMae(formatar("(##) ####-####", clientesArray.get(index).getTelResMae()));
                clientes.setTelCelMae(formatar("(##) #####-####", clientesArray.get(index).getTelCelMae()));

                EnderecosModel em = new EnderecosModel();

                try {
                    Enderecos enderecos = em.byClienteId(clientes.getId());
                    Cidades cidades = new CidadesModel().byId(enderecos.getCidadeId());
                    Estados uf = new EstadosModel().byId(enderecos.getEstadoId());
                    
                    clientes.setEndereco(enderecos.getLogradouro());
                    clientes.setComplemento(enderecos.getComplemento());
                    clientes.setBairro(enderecos.getBairro());
                    clientes.setCep(formatar("#####-###", enderecos.getCep()));
                    clientes.setCidade(cidades.getNome());
                    clientes.setUf(uf.getSigla());
                    
                } catch (SQLException ex) {
                    ex.printStackTrace();
                } catch (ClassNotFoundException ex) {
                    ex.printStackTrace();
                }
                
                dados.add(clientes);
                relatorio = "relatorios/RelatorioClienteEspecifico.jrxml";
            }

            emitirRelatorio(dados, arquivo, relatorio);

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        int index = jComboBox1.getSelectedIndex();
        if (index == 0) {
            jComboBox2.setVisible(false);
        } else {
            jComboBox2.setVisible(true);
            fillClientes(index);
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged
    private void fillClientes(int tipo) {
        DefaultComboBoxModel comboBoxModel = new DefaultComboBoxModel();
        jComboBox2.removeAllItems();

        for (Clientes clientes : clientesArray) {
            if (tipo == 1) {
                comboBoxModel.addElement(clientes.getNome() + " - " + clientes.getNomePai());
            } else if (tipo == 2) {
                comboBoxModel.addElement(clientes.getNome() + " - " + clientes.getNomeMae());
            }

        }
        jComboBox2.setModel(comboBoxModel);

    }
    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
