/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigos.telas;

import codigos.bd.beans.Clientes;
import codigos.bd.beans.Produtos;
import codigos.telas.modal.ModalityInternalFrame;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.beans.PropertyVetoException;
import java.util.ArrayList;
import javax.swing.JComponent;
import javax.swing.JInternalFrame;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lucas
 */
public class TabelaBusca extends ModalityInternalFrame {

    private ArrayList<Clientes> clientes;
    private ArrayList<Produtos> produtos;

    /**
     * Creates new form TabelaCliente
     */
    /**
     * Creates new form TabelaCliente
     *
     * @param clientes
     */
    public TabelaBusca(JComponent component, ArrayList<Clientes> clientes, ArrayList<Produtos> produtos) {
        super(component, "", false, true);
        this.clientes = clientes;
        this.produtos = produtos;
        initComponents();
        fillTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setClosable(true);
        setMaximumSize(new java.awt.Dimension(800, 600));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Pai", "Mae"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fillTable() {
        JInternalFrame jInternalFrame = this;
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();

        if (clientes != null) {
            for (Clientes cliente : clientes) {
                model.addRow(new String[]{String.valueOf(cliente.getId()), cliente.getNome(), cliente.getNomePai(), cliente.getNomeMae()});
            }
        } else if (produtos != null) {
            model.setColumnIdentifiers(new String[]{"Id", "Descrição", "Valor", "Quantidade"});
            for (Produtos produto : produtos) {
                model.addRow(new String[]{String.valueOf(produto.getId()), produto.getDescricao(), "R$ " + String.valueOf(produto.getValor()), String.valueOf(produto.getQuantidade())});
            }
        }

        jTable2.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    JTable target = (JTable) e.getSource();
                    ModalityInternalFrame.linha = target.getSelectedRow();
                    try {
                        jInternalFrame.setClosed(true);
                    } catch (PropertyVetoException ex) {
                        ex.printStackTrace();
                    }
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
